version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HYPERBROWSER_API_KEY=${HYPERBROWSER_API_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    command: /start_celery.sh
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HYPERBROWSER_API_KEY=${HYPERBROWSER_API_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_beat
    command: /start_celery.sh
    env_file:
      - .env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HYPERBROWSER_API_KEY=${HYPERBROWSER_API_KEY}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
